// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ProductID int32              `json:"product_id"`
	Price     pgtype.Numeric     `json:"price"`
	Currency  string             `json:"currency"`
	Stock     int32              `json:"stock"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID        int32              `json:"id"`
	ProductID int32              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	Total     pgtype.Numeric     `json:"total"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
