// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ProductID   int32              `json:"product_id"`
	ProductName string             `json:"product_name"`
	Price       pgtype.Numeric     `json:"price"`
	Currency    string             `json:"currency"`
	Stock       int32              `json:"stock"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID        int32              `json:"id"`
	ProductID int32              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	Total     pgtype.Numeric     `json:"total"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
